### ISSUE TITLE
PHP error occurs when clicking on the RDF tab in content section

### ISSUE THREAD

**Issue by ansergeyg** [openeuropa/oe_content#180]
After following the installation manual (latest release):

Go to http://web:8080/build/en/admin/content:
and click on the RDF link:
```

[Tue Mar 24 14:02:03.568295 2020] [core:notice] [pid 20:tid 140459469138880] AH00094: Command line: 'apache2 -D FOREGROUND'
[Tue Mar 24 14:55:28.727995 2020] [proxy_fcgi:error] [pid 24:tid 140459179468544] [client 192.168.48.1:52674] AH01071: Got error 'PHP message: TypeError: Return value of
Drupal\\rdf_entity\\RdfGraphHandler::getEntityTypeGraphUris() must be of the type array, null returned in /var/www/html/build/modules/contrib/rdf_entity/src/RdfGraphHandler.php on line 164 #0 /var/www/html/build/modules/contrib/rdf_entity/src/RdfGraphHandler.php(182):
 Drupal\\rdf_entity\\RdfGraphHandler->getEntityTypeGraphUris('rdf_entity', Array)\n#1 /var/www/html/build/modules/contrib/rdf_entity/src/Entity/Query/Sparql/Query.php(203): Drupal\\rdf_entity\\RdfGraphHandler->getEntityTypeGraphUrisFlatList('rdf_entity', Array)\n#2 /var/www/html/build/modules/contrib/rdf_entity/src/Entity/Query/Sparql/Query.php(149): 
Drupal\\rdf_entity\\Entity\\Query\\Sparql\\Query->prepare()\n#3 /var/www/html/build/modules/contrib/rdf_entity/src/Entity/Controller/RdfListBuilder.php(94): 
Drupal\\rdf_entity\\Entity\\Query\\Sparql\\Query->execute()\n#4 /var/www/html/build/core/lib/Drupal/Core/Entity/EntityListBuilder.php(86): 
Drupal\\rdf_entity\\Entity\\Controller\\RdfListBuilder->getEntityIds()\n#5 /var/...', referer: http://web:8080/build/en/admin/content
```
Regards, Sergey

**Comment by brummbar** [comment]
This was fixed when we changed to sparql_entity_storage, which doesn't expose the RDF link anymore.
